- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "Passenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    jumpsuit: SWClothingUniformJumpsuitPlayer
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetGrey
  innerclothingskirt: SWClothingUniformJumpskirtPlayer
